"""Generate model configs for the capacity ladder.

A single scalar `width` scales every channel dimension in the shared core:
the ResNet stem, both residual stages, the modulator embedding, and the
ConvGRU hidden state. Readout parameters are set per-session at build time
and are not touched here.

Channel counts are rounded to a multiple of `ROUND_TO` so that the scaled
models stay tensor-core friendly; the realized parameter count is therefore
not exactly quadratic in `width`. Always read realized counts from
`measure_model()` rather than predicting them.

Usage
-----
    from paper.model_selection.gen_configs import write_ladder
    paths = write_ladder()          # writes configs/width_*.yaml
"""
from __future__ import annotations

import copy
from pathlib import Path

import yaml

from VisionCore.paths import VISIONCORE_ROOT

HERE = Path(__file__).resolve().parent
CONFIG_DIR = HERE / "configs"

# The architecture the paper model uses. All ladder rungs are this config
# with the core channel dimensions scaled.
BASE_MODEL_CONFIG = (
    VISIONCORE_ROOT / "experiments" / "model_configs"
    / "learned_resnet_concat_convgru_gaussian.yaml"
)

# Width ladder. 1.0 reproduces the current paper model (4.92M params).
# Spans below and above it so the val-loss curve has a left arm and can be
# pushed past the ~80M saturation point reported for mouse visual cortex
# foundation models (Willeke et al. 2026).
WIDTH_LADDER = (0.25, 0.5, 1.0, 2.0, 3.0, 4.0)

ROUND_TO = 4
MIN_CHANNELS = 4


def _scale(value: int, width: float) -> int:
    """Scale a channel count, rounded to a multiple of ROUND_TO."""
    scaled = value * width
    rounded = int(round(scaled / ROUND_TO) * ROUND_TO)
    return max(MIN_CHANNELS, rounded)


def scale_model_config(config: dict, width: float) -> dict:
    """Return a copy of `config` with all core channel dimensions scaled.

    Scales, in order: ResNet stem output channels, the per-stage residual
    block channels, the modulator feature embedding, and the ConvGRU hidden
    dimension. Kernel sizes, normalization, activations, pooling and the
    regularization schedule are left untouched, so the only thing varying
    across the ladder is capacity.
    """
    cfg = copy.deepcopy(config)

    convnet = cfg["convnet"]["params"]
    convnet["channels"] = [_scale(c, width) for c in convnet["channels"]]
    convnet["stem_config"]["out_channels"] = _scale(
        convnet["stem_config"]["out_channels"], width
    )

    if "modulator" in cfg and cfg["modulator"] is not None:
        mod = cfg["modulator"].get("params", {})
        if "feature_dim" in mod:
            # behavior_dim is set by the dataset (42-d gaze vector); only the
            # learned embedding width scales.
            mod["feature_dim"] = _scale(mod["feature_dim"], width)

    if "recurrent" in cfg and cfg["recurrent"] is not None:
        rec = cfg["recurrent"].get("params", {})
        if "hidden_dim" in rec:
            rec["hidden_dim"] = _scale(rec["hidden_dim"], width)

    return cfg


def width_name(width: float) -> str:
    """Filesystem-safe name for a ladder rung, e.g. 0.25 -> 'width0p25'."""
    return "width" + f"{width:g}".replace(".", "p")


def write_ladder(widths=WIDTH_LADDER, base=BASE_MODEL_CONFIG,
                 out_dir=CONFIG_DIR) -> dict[float, Path]:
    """Write one model config per width. Returns {width: path}."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with open(base) as fh:
        base_cfg = yaml.safe_load(fh)

    paths = {}
    for width in widths:
        cfg = scale_model_config(base_cfg, width)
        path = out_dir / f"{width_name(width)}.yaml"
        header = (
            f"# Capacity-ladder rung: width={width:g}\n"
            f"# Generated by paper/model_selection/gen_configs.py\n"
            f"# Base: {Path(base).name}\n"
        )
        with open(path, "w") as fh:
            fh.write(header)
            yaml.safe_dump(cfg, fh, sort_keys=False)
        paths[width] = path
    return paths


if __name__ == "__main__":
    for width, path in write_ladder().items():
        print(f"width={width:g}  ->  {path}")
