#!/usr/bin/env python3
"""Launch reproducible 240 Hz Dekel-core training runs.

Invoke this script from the ``yatesfv`` conda environment.  It records the
exact command and run specification beside every checkpoint directory before
handing off to the standard single-GPU trainer.

Examples
--------
conda run --no-capture-output -n yatesfv python \
    paper/model_selection/launch_dekel.py D240W1c --gpu 0
conda run --no-capture-output -n yatesfv python \
    paper/model_selection/launch_dekel.py D240T1c --gpu 1
conda run --no-capture-output -n yatesfv python \
    paper/model_selection/launch_dekel.py D240W2c --gpu 1
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
CHECKPOINT_ROOT = Path(
    "/mnt/ssd/YatesMarmoV1/conv_model_fits/experiments/dekel240"
)
M16_CHECKPOINT = (
    "/mnt/ssd/YatesMarmoV1/conv_model_fits/experiments/dekel240/"
    "D240M16c_dekel_freqmasked_floor0p5_smoothonly_05opt_mlp_s201/"
    "analysis_candidates/epoch=415-val_bps_overall=0.5999.ckpt"
)
DATA_CONFIG = "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml"

STEPS_PER_EPOCH = 512
BATCH_SIZE = 512
SAMPLE_BUDGET = 32_000_000
MAX_EPOCHS = round(SAMPLE_BUDGET / (STEPS_PER_EPOCH * BATCH_SIZE))


RUNS = {
    "D240W1c": {
        "name": "D240W1c_dekel_wide_noadapter_reg_mlp_s201",
        "model_config": "experiments/model_configs/dekel_multisession_mlp_behavior.yaml",
        "description": "8/48 width; no adapter; active-session Dekel regularization; MLP additive + FiLM behavior",
    },
    "D240T1c": {
        "name": "D240T1c_dekel_teacherwidth_noadapter_reg_mlp_s201",
        "model_config": "experiments/model_configs/dekel_teacherwidth_mlp_behavior.yaml",
        "description": "exact 4/24 teacher width; no adapter; active-session Dekel regularization; MLP additive + FiLM behavior",
    },
    "D240W2c": {
        "name": "D240W2c_dekel_wide_noadapter_lowprox_mlp_s201",
        "model_config": "experiments/model_configs/dekel_multisession_mlp_behavior_lowprox.yaml",
        "description": "8/48 width; no adapter; unchanged Laplacian smoothness with 0.3x competitive proximal shrinkage; MLP additive + FiLM behavior",
    },
    "D240W3c": {
        "name": "D240W3c_dekel_wide_noadapter_noprox_lr1e3_mlp_s201",
        "model_config": "experiments/model_configs/dekel_multisession_mlp_behavior_noprox.yaml",
        "learning_rate": "0.001",
        "description": "8/48 width; no adapter; unchanged Laplacian smoothness, no competitive proximal shrinkage, historical Dekel 1e-3 learning rate; MLP additive + FiLM behavior",
    },
    "D240M1c": {
        "name": "D240M1c_dekel_wide_240in120target_noprox_lr1e3_mlp_s201",
        "model_config": "experiments/model_configs/dekel_multisession_mlp_behavior_noprox.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.001",
        "description": "8/48 width; native 240 Hz 60-frame input with 120 Hz count supervision; unchanged Laplacian smoothness, no competitive proximal shrinkage, 1e-3 learning rate; MLP additive + FiLM behavior",
    },
    "D240M2c": {
        "name": "D240M2c_dekel_wide_240in120target_noprox_lr3e3_mlp_s201",
        "model_config": "experiments/model_configs/dekel_multisession_mlp_behavior_noprox.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.003",
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "8/48 width; native 240 Hz 60-frame input with 120 Hz count supervision; unchanged Laplacian smoothness, no competitive proximal shrinkage, F3c-style 3e-3 learning rate and norm clipping; MLP additive + FiLM behavior",
    },
    "D240M3c": {
        "name": "D240M3c_dekel_capacitymatched_240in120target_ramped_lr1e3_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_ramped_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.001",
        "description": "14/84 capacity-matched Dekel core (5.07M parameters); native 240 Hz 60-frame input with 120 Hz count supervision; hidden smoothness ramped from epochs 4-12; 64-channel nonrecurrent MLP behavior",
    },
    "D240M4c": {
        "name": "D240M4c_dekel_capacitymatched_240in120target_ramped_lr5e4_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_ramped_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "description": "14/84 capacity-matched Dekel core (5.07M parameters); same delayed structural prior as M3; Figure-3 starting learning rate 5e-4; 64-channel nonrecurrent MLP behavior",
    },
    "D240M5c": {
        "name": "D240M5c_dekel_capacitymatched_freqmasked_240in120target_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Capacity-matched no-structural-penalty control plus true first-layer Hann frequency masking; exact 05 optimizer cadence (batch 128, no accumulation)",
    },
    "D240M6c": {
        "name": "D240M6c_dekel_capacitymatched_nostructuralreg_240in120target_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Capacity-matched model with all explicit kernel penalties removed; exact 05 optimizer cadence (batch 128, no accumulation)",
    },
    "D240M7c": {
        "name": "D240M7c_dekel_freqmasked_240in120target_head5e4_core1p25e4_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Frequency-masked capacity model with 05 readout/behavior LR 5e-4 but visual-core LR reduced to 1.25e-4",
    },
    "D240M8c": {
        "name": "D240M8c_dekel_freqmasked_240in120target_lr1e4_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Frequency-masked capacity model with all parameter groups reduced to LR 1e-4",
    },
    "D240M9c": {
        "name": "D240M9c_dekel_freqmasked_freshsampler_240in120target_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected fresh-per-epoch sampler; capacity-matched model with true temporal/spatial frequency masking and exact 05 optimizer cadence",
    },
    "D240M10c": {
        "name": "D240M10c_dekel_unmasked_freshsampler_240in120target_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_nostructuralreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected fresh-per-epoch sampler; otherwise matched unmasked control with exact 05 optimizer cadence",
    },
    "D240M11c": {
        "name": "D240M11c_dekel_freqmasked_freshsampler_readoutfloor0p25_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p25_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected sampler and frequency mask; Gaussian readout sigma floored at 0.25 scaffold pixels to prevent delta-readout collapse",
    },
    "D240M12c": {
        "name": "D240M12c_dekel_freqmasked_freshsampler_readoutfloor0p5_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected sampler and frequency mask; Gaussian readout sigma floored at 0.5 scaffold pixels, matching the old teacher's median scale",
    },
    "D240M13c": {
        "name": "D240M13c_dekel_freqmasked_freshsampler_readoutfloor0p75_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p75_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected sampler and frequency mask; Gaussian readout sigma floored at 0.75 scaffold pixels to bracket Ryan 05's median width",
    },
    "D240M14c": {
        "name": "D240M14c_dekel_freqmasked_floor0p5_scaleddekelreg_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_scaleddekelreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Corrected sampler, frequency mask, 0.5-pixel readout floor, and width-scaled ramped Dekel smoothness/competition priors",
    },
    "D240M15c": {
        "name": "D240M15c_dekel_freqmasked_floor0p5_halfscaleddekelreg_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_halfscaleddekelreg_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Half-strength width-scaled smoothness and competition priors to test the accuracy/smoothness midpoint",
    },
    "D240M16c": {
        "name": "D240M16c_dekel_freqmasked_floor0p5_smoothonly_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_smoothonly_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Full width-scaled Laplacian priors without hidden/readout competition to isolate the source of the accuracy gap",
    },
    "D240M17c": {
        "name": "D240M17c_dekel_freqmasked_floor0p5_halfsmoothonly_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_halfsmoothonly_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Half-strength width-scaled Laplacian priors without competition to map the clean accuracy/smoothness dose response",
    },
    "D240M18c": {
        "name": "D240M18c_dekel_freqmasked_floor0p5_fulltemporal_halfspatial_smoothonly_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_fulltemporal_halfspatial_smoothonly_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Full temporal and half spatial width-scaled Laplacian priors without competition, targeting clean temporal Jacobians with less accuracy cost",
    },
    "D240M19c": {
        "name": "D240M19c_dekel_freqmasked_floor0p5_2xspatial_smoothonly_05opt_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_2xspatial_smoothonly_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "Epoch-127 fine-tuning branch with unchanged temporal and doubled spatial Laplacian strength, testing whether late spatial Jacobian roughening can be reversed without an accuracy penalty",
    },
    "D240M20a": {
        "name": "D240M20a_m16frozen_outputbehavior_additive_s201",
        "model_config": "experiments/model_configs/dekel_m16_output_behavior_additive.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.001",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 40,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_checkpoint": M16_CHECKPOINT,
        "pretrained_scope": "compatible",
        "freeze_pretrained": True,
        "description": "M16 epoch 415 frozen exactly; train only a shared low-rank neuron-specific additive behavior residual",
    },
    "D240M20b": {
        "name": "D240M20b_m16frozen_outputbehavior_gainadd_s201",
        "model_config": "experiments/model_configs/dekel_m16_output_behavior_gain_additive.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.001",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 40,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_checkpoint": M16_CHECKPOINT,
        "pretrained_scope": "compatible",
        "freeze_pretrained": True,
        "description": "M16 epoch 415 frozen exactly; train only a shared low-rank neuron-specific bounded-gain plus additive behavior residual",
    },
    "D240M21a": {
        "name": "D240M21a_surround51_scaffold13_jointrefine_s201",
        "model_config": "experiments/model_configs/dekel_m21_surround51_output_behavior_gain_additive.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 64,
        "accumulate_grad_batches": 2,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "requires_pretrained_checkpoint": True,
        "description": "Warm-start selected M20 into a 51-pixel aperture and 13x13 scaffold; gently refine all weights with mature M16 smoothness priors",
    },
    "D240M22a": {
        "name": "D240M22a_m20_readout_outputbehavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m22_readout_outputbehavior_refine.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze the selected M20 visual and feature-behavior representation; co-adapt only Gaussian readouts and the bounded output behavior residual",
    },
    "D240M23a": {
        "name": "D240M23a_m20_fixedvision_behavior_readout_refine_s201",
        "model_config": "experiments/model_configs/dekel_m22_readout_outputbehavior_refine.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Keep the frequency-masked visual core fixed; gently co-adapt the smooth feature-space behavior path, Gaussian readouts, and output behavior residual",
    },
    "D240M24a": {
        "name": "D240M24a_m16frozen_dualgrid_outputbehavior_gainadd_s201",
        "model_config": "experiments/model_configs/dekel_m16_output_behavior_gain_additive.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_dualbehavior.yaml",
        "learning_rate": "0.001",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 40,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_checkpoint": M16_CHECKPOINT,
        "pretrained_scope": "compatible",
        "freeze_pretrained": True,
        "description": "Freeze M16 exactly and fit the output residual on a separate behavior tensor reconstructed on Ryan's original 120-Hz preprocessing grid",
    },
    "D240M25a": {
        "name": "D240M25a_m16frozen_nativeplusryangrid_outputbehavior_s201",
        "model_config": "experiments/model_configs/dekel_m16_output_behavior_gain_additive_dual84.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_dualbehavior.yaml",
        "learning_rate": "0.001",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 48,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_checkpoint": M16_CHECKPOINT,
        "pretrained_scope": "compatible",
        "freeze_pretrained": True,
        "description": "Freeze M16 and let a slightly wider output residual use both the native M16 and reconstructed Ryan-grid behavior tensors",
    },
    "D240M26a": {
        "name": "D240M26a_m20_fixedvision_ryangrid_behavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m22_readout_outputbehavior_refine.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Keep the smooth visual core fixed while retraining feature behavior, readouts, and output residual on Ryan's original 120-Hz behavior grid",
    },
    "D240M27a": {
        "name": "D240M27a_m25_fixedvision_surround51_dualbehavior_s201",
        "model_config": "experiments/model_configs/dekel_m27_surround51_dual84_fixedvision.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_dualbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Expand M25 to the raw 51-pixel aperture while keeping every visual-core parameter fixed; retrain behavior and Gaussian readouts on the 13x13 scaffold",
    },
    "D240M28a": {
        "name": "D240M28a_m25_fixedvision_biasless_ryangrid_purefilm_s201",
        "model_config": "experiments/model_configs/dekel_m28_biasless_purefilm_dual84.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_dualbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "modulator",
        "pretrained_shape_adaptation": "trim_readout_features",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Keep M16 visual filters fixed, replace its nearly constant feature behavior path with fresh biasless Ryan-grid FiLM, retain M25's dual-grid output residual, and co-adapt Gaussian readouts",
    },
    "D240M29a": {
        "name": "D240M29a_m28_fixedvision_surround51_biaslessfilm_s201",
        "model_config": "experiments/model_configs/dekel_m29_surround51_biasless_purefilm_dual84.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_dualbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Expand a selected biasless-FiLM checkpoint to the raw 51-pixel aperture while freezing every visual kernel and adapting behavior/readout parameters",
    },
    "D240M30a": {
        "name": "D240M30a_m29_surround51_jointrefine_s201",
        "model_config": "experiments/model_configs/dekel_m30_surround51_jointrefine.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_dualbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "requires_pretrained_checkpoint": True,
        "description": "Gently refine the full wider successor at 2.5e-5 visual-core LR under mature M16 spatial/temporal smoothness and the existing frequency masks",
    },
    "D240M31a": {
        "name": "D240M31a_m26_fixedvision_surround51_ryanbehavior_s201",
        "model_config": "experiments/model_configs/dekel_m31_surround51_ryanbehavior_fixedvision.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Expand the strongest Ryan-grid behavior branch to 51 pixels, preserve every smooth visual kernel, and adapt behavior plus Gaussian readouts on the wider scaffold",
    },
    "D240M31b": {
        "name": "D240M31b_m26_fixedvision_surround51_scaledreadout_ryanbehavior_s201",
        "model_config": "experiments/model_configs/dekel_m31_surround51_ryanbehavior_fixedvision.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.5",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_shape_adaptation": "scale_gaussian_readout",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Expand M26 to 51 pixels while rescaling Gaussian centers/widths from the 9x9 to 13x13 scaffold, freezing every visual kernel, and adapting behavior/readouts",
    },
    "D240M32a": {
        "name": "D240M32a_m26_ryanbehavior_jointrefine35_s201",
        "model_config": "experiments/model_configs/dekel_m32_ryanbehavior_jointrefine35.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "requires_pretrained_checkpoint": True,
        "description": "Refine the full 35-pixel Ryan-grid successor at 2.5e-5 visual-core LR under mature spatial/temporal smoothness and frequency masks",
    },
    "D240M33a": {
        "name": "D240M33a_m31_surround51_ryanbehavior_jointrefine_s201",
        "model_config": "experiments/model_configs/dekel_m21_surround51_output_behavior_gain_additive.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 96,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "requires_pretrained_checkpoint": True,
        "description": "Jointly refine the wider Ryan-grid successor with the visual core at 2.5e-5 and mature M16 spatial/temporal priors",
    },
    "D240M34a": {
        "name": "D240M34a_m26_outputbehavior_only_lr5e5_s201",
        "model_config": "experiments/model_configs/dekel_m22_readout_outputbehavior_refine.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Polish only M26's neuron-specific nonlinear behavior residual at 5e-5 while freezing the visual core, feature behavior path, and Gaussian readouts exactly",
    },
    "D240M35a": {
        "name": "D240M35a_m26_session_behavior_adapter_s201",
        "model_config": "experiments/model_configs/dekel_m35_session_adapter_outputbehavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "output_modulator.dataset_adapters",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Freeze M26 exactly and train only zero-initialized rank-8 session-specific corrections to its mature shared output-behavior basis",
    },
    "D240M35b": {
        "name": "D240M35b_m26_session_behavior_adapter_lr2e4_s201",
        "model_config": "experiments/model_configs/dekel_m35_session_adapter_outputbehavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "output_modulator.dataset_adapters",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Lower-learning-rate control for the identity-initialized rank-8 session-specific M26 behavior corrections",
    },
    "D240M36a": {
        "name": "D240M36a_m26_residual_gaussian_readout_s201",
        "model_config": "experiments/model_configs/dekel_m36_residual_gaussian_readout.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "residual_readouts",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Freeze M26 exactly and fit a zero-initialized second Gaussian visual component per neuron on its smooth feature map",
    },
    "D240M36b": {
        "name": "D240M36b_m26_matched_surround_readout_s201",
        "model_config": "experiments/model_configs/dekel_m36b_matched_surround_readout.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "residual_readouts",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Freeze M26 exactly and fit a bounded signed matched surround that reuses each neuron's mature feature projection",
    },
    "D240M36c": {
        "name": "D240M36c_m26_matched_surround_readout_lr5e4_s201",
        "model_config": "experiments/model_configs/dekel_m36b_matched_surround_readout.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "residual_readouts",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Higher-learning-rate control for the compact identity-initialized matched-surround readout",
    },
    "D240M37a": {
        "name": "D240M37a_m26_population_lowrank_surround_s201",
        "model_config": "experiments/model_configs/dekel_m37_population_lowrank_surround.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0002",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "residual_readouts",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Freeze M26 and fit a rank-4 population-feature mixture under a bounded smooth second Gaussian",
    },
    "D240M37b": {
        "name": "D240M37b_m26_population_lowrank_surround_weakfactorreg_s201",
        "model_config": "experiments/model_configs/dekel_m37b_population_lowrank_surround_weakfactorreg.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "0.25",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "residual_readouts",
        "freeze_pretrained": True,
        "requires_pretrained_checkpoint": True,
        "description": "Corrected rank-4 population surround with summed-factor L2 scaled below the Poisson data term",
    },
    "D240M38a": {
        "name": "D240M38a_m26_auxiliary_teacherwidth_visual_boost_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 256,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "auxiliary_convnet,auxiliary_readouts",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "auxiliary_convnet,auxiliary_readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze M26 exactly and boost only its visual residual with a frequency-masked, Laplacian-regularized 4/24 teacher-width Dekel branch",
    },
    "D240M39a": {
        "name": "D240M39a_m26_auxiliary_midwidth_visual_boost_s201",
        "model_config": "experiments/model_configs/dekel_m39_auxiliary_midwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 256,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "auxiliary_convnet,auxiliary_readouts",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "auxiliary_convnet,auxiliary_readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Capacity control for M38: freeze M26 and boost its visual residual with an initial-penalty-matched smooth 8/48 Dekel branch",
    },
    "D240M40a": {
        "name": "D240M40a_m38_joint_readout_outputbehavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze both smooth visual cores from the selected M38 checkpoint and jointly align the base/auxiliary Gaussian readouts plus output behavior head at low learning rate",
    },
    "D240M40b": {
        "name": "D240M40b_m38_constrained_readout_outputbehavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Constrained M40 restart: freeze both visual cores, retain the 0.5-pixel base-readout floor, and align only readouts plus output behavior",
    },
    "D240M41a": {
        "name": "D240M41a_m39_joint_readout_outputbehavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m39_auxiliary_midwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Capacity-control refinement for M39: freeze both visual cores and align only the two Gaussian readouts plus output behavior head at low learning rate",
    },
    "D240M42a": {
        "name": "D240M42a_m26_auxiliary_surround51_visual_boost_s201",
        "model_config": "experiments/model_configs/dekel_m42_auxiliary_surround51_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 256,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "auxiliary_convnet,auxiliary_readouts",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "auxiliary_convnet,auxiliary_readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Preserve M26's 35-pixel center exactly and fit only a frequency-masked, Laplacian-regularized teacher-width residual on the full 51-pixel surround",
    },
    "D240M43a": {
        "name": "D240M43a_m42_joint_readout_outputbehavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m42_auxiliary_surround51_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel51_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze both M42 visual cores and jointly align the center/surround readouts plus output behavior head at low learning rate",
    },
    "D240M45a": {
        "name": "D240M45a_m40_distilled_behavior_refine_s201",
        "model_config": "experiments/model_configs/dekel_m45_m40_distilled_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "distilled_output_modulator",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "distilled_output_modulator",
        "distilled_output_modulator_checkpoint": "outputs/dekel240_distillation/M44_ryan_behavior_full30.pt",
        "requires_pretrained_checkpoint": True,
        "requires_distilled_output_modulator_checkpoint": True,
        "description": "Freeze the selected M40 smooth visual twin exactly and spike-refine only an output-only gain/offset head distilled from Ryan's behavior residual",
    },
    "D240M46a": {
        "name": "D240M46a_m45_constrained_head_coadapt_s201",
        "model_config": "experiments/model_configs/dekel_m45_m40_distilled_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 64,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator,distilled_output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Optional second gate from selected M45: keep both visual cores frozen and co-adapt Gaussian readouts with both output-only behavior heads at 5e-5",
    },
    "D240M47a": {
        "name": "D240M47a_m40_temporal_context66_visual_boost_s201",
        "model_config": "experiments/model_configs/dekel_m47_temporal_context66_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_context66_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "auxiliary_convnet,auxiliary_readouts",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "auxiliary_convnet,auxiliary_readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Preserve M40's mature 60-frame core and fit only a frequency-masked, Laplacian-regularized residual on six additional leading frames",
    },
    "D240M47b": {
        "name": "D240M47b_m40_temporal_context66_visual_boost_s201",
        "model_config": "experiments/model_configs/dekel_m47_temporal_context66_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_context66_ryanbehavior.yaml",
        "learning_rate": "0.0005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "pretrained_exclude_prefixes": "auxiliary_convnet,auxiliary_readouts",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "auxiliary_convnet,auxiliary_readouts",
        "requires_pretrained_checkpoint": True,
        "description": "Corrected lag-order restart: preserve M40's newest 60 frames and fit a smooth residual using six additional older frames",
    },
    "D240M48a": {
        "name": "D240M48a_m40_lowrate_head_continuation_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Continue the still-improving M40 readout and original behavior-head optimization at half the learning rate while both visual cores remain exact",
    },
    "D240M49a": {
        "name": "D240M49a_m40_full_behavior_readout_refine_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.0001",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "modulator,readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze both smooth visual cores from M40 and jointly refine the feature-level behavior path, output behavior residual, and Gaussian readouts",
    },
    "D240M50a": {
        "name": "D240M50a_m47_context66_behavior_readout_refine_s201",
        "model_config": "experiments/model_configs/dekel_m47_temporal_context66_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_context66_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Freeze both visual cores from selected M47 and co-adapt only the output behavior path plus both Gaussian readouts on the 66-frame contract",
    },
    "D240M51a": {
        "name": "D240M51a_m48_relaxed_readoutfloor0p35_s201",
        "model_config": "experiments/model_configs/dekel_m51_relaxed_readout_floor.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "1.0",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 96,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Continue selected M48 with both smooth visual cores frozen while relaxing the base Gaussian floor to 0.35 pixels",
    },
    "D240M52a": {
        "name": "D240M52a_m48_ultralowrate_regularized_visual_refine_s201",
        "model_config": "experiments/model_configs/dekel_m38_auxiliary_teacherwidth_visual_boost.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240in_120target_long_split3_dekel35_ryanbehavior.yaml",
        "learning_rate": "0.00005",
        "core_lr_scale": "0.1",
        "weight_decay": "1e-5",
        "batch_size": 256,
        "accumulate_grad_batches": 1,
        "max_epochs": 128,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "pretrained_scope": "complete",
        "freeze_pretrained": True,
        "trainable_parameter_patterns": "convnet,readouts,output_modulator",
        "requires_pretrained_checkpoint": True,
        "description": "Refine both frequency-masked visual cores from selected M48 at 5e-6 while keeping feature behavior frozen and retaining mature Laplacian priors",
    },
    "D240M73c": {
        "name": "D240M73c_dekel_native240_freqmasked_floor0p5_nostructuralreg_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz one-frame count supervision; capacity-matched frequency-masked core, 0.5-pixel readout floor, and no Laplacian or competitive structural penalty",
    },
    "D240M74c": {
        "name": "D240M74c_dekel_native240_freqmasked_floor0p5_halfsmoothonly_mlp_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_halfsmoothonly_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz one-frame count supervision; matched frequency-masked core and readout with half-strength Laplacian smoothness and no competition",
    },
    "D240M75c": {
        "name": "D240M75c_dekel_native240_freqmasked_floor0p5_lrn_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_lrn_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz matched M73 control replacing aperture-global pair-aligned GroupNorm with sign-paired LocalResponseNorm(size=5)",
    },
    "D240M76c": {
        "name": "D240M76c_dekel_native240_freqmasked_floor0p5_historical_gnlrn_presplit_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_groupnorm_lrn_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz matched M73 control using Dekel's historical GroupNorm -> LocalResponseNorm(size=5) -> sign split -> ReLU ordering",
    },
    "D240M77c": {
        "name": "D240M77c_dekel_native240_freqmasked_floor0p5_gnlrnalpha0p1_presplit_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_groupnorm_lrnalpha0p1_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz M76 control with functionally meaningful moderate LRN(alpha=0.1) after pre-split GroupNorm",
    },
    "D240M78c": {
        "name": "D240M78c_dekel_native240_freqmasked_floor0p5_gnlrnalpha0p03_presplit_s201",
        "model_config": "experiments/model_configs/dekel_capacitymatched_freqmasked_readoutfloor0p5_groupnorm_lrnalpha0p03_mlp_behavior.yaml",
        "dataset_config": "paper/model_selection/configs/multi_240_long_split3_dekel35.yaml",
        "learning_rate": "0.0005",
        "weight_decay": "1e-5",
        "batch_size": 128,
        "accumulate_grad_batches": 1,
        "max_epochs": 488,
        "gradient_clip_val": "10.0",
        "gradient_clip_algorithm": "norm",
        "description": "True native-240-Hz interpolation between M76 and M77, using pre-split GroupNorm followed by moderate LocalResponseNorm(alpha=0.03)",
    },
}


def build_command(spec, gpu: int, resume: str | None = None):
    batch_size = int(spec.get("batch_size", BATCH_SIZE))
    max_epochs = int(spec.get("max_epochs", MAX_EPOCHS))
    accumulate_grad_batches = int(spec.get("accumulate_grad_batches", 1))
    cmd = [
        sys.executable,
        "training/train_multidataset.py",
        "--model_config", spec["model_config"],
        "--dataset_configs_path", spec.get("dataset_config", DATA_CONFIG),
        "--max_datasets", "30",
        "--batch_size", str(batch_size),
        "--learning_rate", spec.get("learning_rate", "0.0005"),
        "--core_lr_scale", spec.get("core_lr_scale", "1.0"),
        "--weight_decay", spec.get("weight_decay", "0"),
        "--lr_scheduler", "cosine_warmup",
        "--warmup_epochs", "2",
        "--max_epochs", str(max_epochs),
        "--accumulate_grad_batches", str(accumulate_grad_batches),
        "--steps_per_epoch", str(STEPS_PER_EPOCH),
        "--gradient_clip_val", spec.get("gradient_clip_val", "0.5"),
        "--gradient_clip_algorithm", spec.get("gradient_clip_algorithm", "value"),
        "--precision", "bf16-mixed",
        "--dset_dtype", "uint8",
        "--num_workers", "16",
        "--limit_val_batches", "0.1",
        "--check_val_every_n_epoch", "4",
        "--seed", "201",
        "--gpu", str(gpu),
        "--checkpoint_dir", str(CHECKPOINT_ROOT),
        "--project_name", "model_selection",
        "--experiment_name", spec["name"],
        "--no-early_stopping",
        "--homogeneous_batches",
        "--enable_logging",
        "--fast_log_interval", "5",
        # Kernel panels are useful during fitting; the legacy full eval stack
        # is intentionally deferred to checkpoint evaluation.
        "--slow_log_interval", "10000",
        "--log_dataset_idx", "9",
    ]
    if resume is not None:
        cmd += ["--ckpt_path", resume]
    if spec.get("pretrained_checkpoint"):
        cmd += ["--pretrained_checkpoint", spec["pretrained_checkpoint"]]
    if spec.get("pretrained_scope"):
        cmd += ["--pretrained_scope", spec["pretrained_scope"]]
    if spec.get("freeze_vision", False):
        cmd += ["--freeze_vision"]
    if spec.get("freeze_pretrained", False):
        cmd += ["--freeze_pretrained"]
    if spec.get("trainable_parameter_patterns"):
        cmd += [
            "--trainable_parameter_patterns",
            spec["trainable_parameter_patterns"],
        ]
    if spec.get("pretrained_exclude_prefixes"):
        cmd += [
            "--pretrained_exclude_prefixes",
            spec["pretrained_exclude_prefixes"],
        ]
    if spec.get("pretrained_shape_adaptation"):
        cmd += [
            "--pretrained_shape_adaptation",
            spec["pretrained_shape_adaptation"],
        ]
    if spec.get("distilled_output_modulator_checkpoint"):
        cmd += [
            "--distilled_output_modulator_checkpoint",
            spec["distilled_output_modulator_checkpoint"],
        ]
    return cmd


def write_manifest(run_id: str, spec, cmd):
    batch_size = int(spec.get("batch_size", BATCH_SIZE))
    max_epochs = int(spec.get("max_epochs", MAX_EPOCHS))
    accumulate_grad_batches = int(spec.get("accumulate_grad_batches", 1))
    samples_actual = max_epochs * STEPS_PER_EPOCH * batch_size
    run_dir = CHECKPOINT_ROOT / spec["name"]
    run_dir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "run_id": run_id,
        "name": spec["name"],
        "description": spec["description"],
        "launched": datetime.now().isoformat(timespec="seconds"),
        "sample_budget": samples_actual,
        "samples_actual": samples_actual,
        "batch_size": batch_size,
        "accumulate_grad_batches": accumulate_grad_batches,
        "steps_per_epoch": STEPS_PER_EPOCH,
        "max_epochs": max_epochs,
        "dataset_config": spec.get("dataset_config", DATA_CONFIG),
        "command": cmd,
    }
    path = run_dir / "manifest.json"
    if "--ckpt_path" in cmd and path.exists():
        # Preserve the original launch contract and append each continuation.
        # Overwriting the manifest during a resume would erase the exact warm
        # start and sample history that produced the checkpoint being resumed.
        existing = json.loads(path.read_text())
        existing.setdefault("resume_history", []).append(
            {
                "launched": manifest["launched"],
                "command": cmd,
                "resume_checkpoint": cmd[cmd.index("--ckpt_path") + 1],
            }
        )
        existing["last_launched"] = manifest["launched"]
        existing["last_command"] = cmd
        path.write_text(json.dumps(existing, indent=2))
        return path
    path.write_text(json.dumps(manifest, indent=2))
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run", nargs="?", choices=sorted(RUNS))
    parser.add_argument("--gpu", type=int, choices=[0, 1], default=0)
    parser.add_argument("--resume", type=str, default=None)
    parser.add_argument(
        "--pretrained-checkpoint",
        type=str,
        default=None,
        help="Override the run's warm-start checkpoint (required by successor runs)",
    )
    parser.add_argument(
        "--distilled-output-modulator-checkpoint",
        type=str,
        default=None,
        help="Override the standalone behavior-residual initialization artifact",
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--list", action="store_true")
    args = parser.parse_args()

    if args.list or args.run is None:
        print(
            f"{MAX_EPOCHS} epochs x {STEPS_PER_EPOCH} x {BATCH_SIZE} = "
            f"{MAX_EPOCHS * STEPS_PER_EPOCH * BATCH_SIZE:,} samples"
        )
        for run_id, spec in RUNS.items():
            print(f"{run_id}: {spec['name']} -- {spec['description']}")
        return

    spec = dict(RUNS[args.run])
    if args.pretrained_checkpoint is not None:
        spec["pretrained_checkpoint"] = args.pretrained_checkpoint
    if args.distilled_output_modulator_checkpoint is not None:
        spec["distilled_output_modulator_checkpoint"] = (
            args.distilled_output_modulator_checkpoint
        )
    if (
        spec.get("requires_pretrained_checkpoint", False)
        and not spec.get("pretrained_checkpoint")
    ):
        parser.error(
            f"{args.run} requires --pretrained-checkpoint pointing to the "
            "selected predecessor checkpoint"
        )
    if (
        spec.get("requires_distilled_output_modulator_checkpoint", False)
        and not spec.get("distilled_output_modulator_checkpoint")
    ):
        parser.error(
            f"{args.run} requires --distilled-output-modulator-checkpoint "
            "pointing to the selected standalone behavior artifact"
        )
    cmd = build_command(spec, args.gpu, args.resume)
    print(f"[{args.run}] {spec['description']}")
    print(" ".join(cmd))
    if args.dry_run:
        return

    manifest = write_manifest(args.run, spec, cmd)
    print(f"manifest -> {manifest}")
    raise SystemExit(subprocess.call(cmd, cwd=ROOT))


if __name__ == "__main__":
    main()
